[package]
name = "timezz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.3.1"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_14"] }
notify-rust = "4.11.0"
